# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.22.2
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
a.size * a.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
print(a)
a = a[::-1]
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a = np.array([1,2,0,0,4,0])
a[a.nonzero()]

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
a = np.random.random((3,3,3))
a

array([[[0.29445862, 0.89471569, 0.58349405],
        [0.42835233, 0.78524573, 0.68213395],
        [0.09717869, 0.47188944, 0.96998034]],

       [[0.2638822 , 0.55448658, 0.26569054],
        [0.32901776, 0.42950635, 0.96306076],
        [0.65184606, 0.32205238, 0.55359089]],

       [[0.66047618, 0.76147121, 0.52393463],
        [0.39010005, 0.03864939, 0.66503128],
        [0.10630807, 0.39921126, 0.71344774]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.random((10, 10))
print(a)
print('Min is', a.min())
print('Max is', a.max())

[[0.22375153 0.5911721  0.80649878 0.99560761 0.69357329 0.17362482
  0.50050112 0.36440401 0.63052986 0.29511585]
 [0.8352538  0.31880421 0.93978955 0.12601719 0.38498872 0.74244804
  0.62064865 0.89847147 0.38201672 0.53224947]
 [0.98453982 0.59668126 0.03789111 0.66659991 0.40585907 0.51817306
  0.4964466  0.20015253 0.02603879 0.82529107]
 [0.0727499  0.02771237 0.87077756 0.95337541 0.07273307 0.72000752
  0.53268136 0.02092969 0.79841927 0.33105099]
 [0.25501863 0.1456915  0.87724827 0.88580771 0.68890923 0.84309075
  0.08330589 0.88709756 0.50769805 0.91942368]
 [0.64050165 0.95135687 0.7399649  0.71431794 0.92969301 0.12245342
  0.96535398 0.80624288 0.60637426 0.65631581]
 [0.56832965 0.4836826  0.63615245 0.36635242 0.1719278  0.85562087
  0.76019493 0.03692121 0.7349573  0.03383796]
 [0.39567005 0.39109146 0.78161964 0.46095983 0.79138208 0.39130113
  0.26251953 0.94547924 0.50841554 0.44475238]
 [0.31338509 0.24468756 0.81228645 0.59071611 0.41913959 0.69983775
  0.84017059

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
a = np.random.random((30))
print(a)
a.mean()

[0.80554331 0.6957608  0.43080685 0.2410271  0.38386339 0.11796036
 0.69946944 0.71642398 0.58335988 0.27736019 0.63892107 0.35160387
 0.04982723 0.37675913 0.06188932 0.91689578 0.67180702 0.97086742
 0.64815886 0.11276194 0.48677203 0.13427118 0.65915443 0.95013038
 0.38941904 0.14050855 0.10394864 0.17950661 0.20946244 0.44861032]


0.44842835171647405

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a = np.ones((10, 10))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.ones((3, 3))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
a = np.diag([1,2,3,4], k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a = np.tile(np.array([[0,1], [1,0]]), (4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.random((5, 5))
print(a)
a = (a - a.mean())/(a.max()-a.min())
a

[[0.58120142 0.31824558 0.90092515 0.11538659 0.56818956]
 [0.3542125  0.11446863 0.22874771 0.57568822 0.1411187 ]
 [0.6199302  0.60645392 0.08679216 0.55440276 0.44962088]
 [0.28976484 0.06656638 0.09637923 0.42625568 0.27966837]
 [0.82965502 0.64922208 0.94770726 0.29900163 0.26130886]]


array([[ 0.18926018, -0.10916637,  0.55211219, -0.33938947,  0.17449313],
       [-0.0683478 , -0.34043126, -0.21073682,  0.1830033 , -0.31018631],
       [ 0.23321318,  0.21791906, -0.37184108,  0.1588466 ,  0.03993045],
       [-0.14148894, -0.39479516, -0.36096079,  0.01341345, -0.15294735],
       [ 0.47122826,  0.26645631,  0.60520484, -0.13100619, -0.17378342]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
RGBA = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
RGBA

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a = 100 * np.random.random((5, 3))
b = 100 * np.random.random((3, 2))
a @ b

array([[ 4066.01609397,  6223.62674559],
       [ 3328.95542961,  7380.80011521],
       [ 4351.10089331, 10138.1358448 ],
       [ 2631.24674012,  7219.07435731],
       [ 2528.97342719,  8821.15949221]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
a = np.arange(20)
a[3:9] = a[3:9] * (-1)
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [96]:
Z = np.arange(10, dtype = int)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\t041l\AppData\Local\Temp\ipykernel_7688\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\t041l\AppData\Local\Temp\ipykernel_7688\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
a = 10 * np.random.random(10)
a = np.where(a>0, np.ceil(a), np.floor(a))
a

array([ 7.,  4.,  5.,  1.,  9., 10., 10.,  7.,  1.,  7.])

#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
a = np.arange(10)
b = np.arange(7, 13)
print(np.intersect1d(a,b))

[7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1))

2023-04-02
2023-04-03
2023-04-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
a

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
A = np.ones(5)*10
B = np.ones(5)*20
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-150., -150., -150., -150., -150.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
a = 100 * np.random.random(10)
print(a)
print(a.astype(int))
print(np.floor(a))
print(a - a%1)
print(a // 1)

[49.90950992 17.89016522 28.20613126  1.9639186  55.69848302  2.33788124
 81.68585541 12.34711908 55.52833168 70.5958219 ]
[49 17 28  1 55  2 81 12 55 70]
[49. 17. 28.  1. 55.  2. 81. 12. 55. 70.]
[49. 17. 28.  1. 55.  2. 81. 12. 55. 70.]
[49. 17. 28.  1. 55.  2. 81. 12. 55. 70.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
a = np.zeros((5,5))
a += np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def gen_nums():
    for i in range(10):
        yield i

a = np.fromiter(gen_nums(), dtype = int)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
a = np.linspace(0, 1, 11, endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
a = np.random.random(10)
a.sort()
a

array([0.19253256, 0.25490273, 0.29723341, 0.39333977, 0.51247781,
       0.59153679, 0.63181657, 0.70595984, 0.85747185, 0.90455193])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
a = np.arange(5)
np.add.reduce(a)

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [43]:
A = np.random.randint(0, 100, 10)
B = np.random.randint(0, 100, 10)
print(A)
print(B)
np.array_equal(A, B)

[51 93  2 59 24 51 58 89 51 46]
[90 48 90 53 19 45 69 52 53 72]


False

#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
a = np.arange(0, 10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
matrix = np.random.random((10,2))
X,Y = matrix[:,0], matrix[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.47994029 0.92915649 0.80026875 0.57138669 1.1384784  1.26883032
 0.22011709 0.54170107 0.44194243 0.83424029]
[1.15157775 0.45324426 0.64842428 0.3723324  0.80302763 0.78995033
 0.17633839 0.98326718 0.38137841 1.25198914]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.27876385, 0.3232635 , 0.88373417, 0.50555856, 0.35515693,
       0.75157906, 0.682046  , 0.22521298, 0.9261196 , 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
vector = np.zeros((6,6), [('x',float),('y',float)])
vector['x'], vector['y'] = np.meshgrid(np.linspace(0,1,6),
                             np.linspace(0,1,6))
print(vector)

[[(0. , 0. ) (0.2, 0. ) (0.4, 0. ) (0.6, 0. ) (0.8, 0. ) (1. , 0. )]
 [(0. , 0.2) (0.2, 0.2) (0.4, 0.2) (0.6, 0.2) (0.8, 0.2) (1. , 0.2)]
 [(0. , 0.4) (0.2, 0.4) (0.4, 0.4) (0.6, 0.4) (0.8, 0.4) (1. , 0.4)]
 [(0. , 0.6) (0.2, 0.6) (0.4, 0.6) (0.6, 0.6) (0.8, 0.6) (1. , 0.6)]
 [(0. , 0.8) (0.2, 0.8) (0.4, 0.8) (0.6, 0.8) (0.8, 0.8) (1. , 0.8)]
 [(0. , 1. ) (0.2, 1. ) (0.4, 1. ) (0.6, 1. ) (0.8, 1. ) (1. , 1. )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [48]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [49]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [50]:
a = np.random.random(5)
print(*a)

0.5203357952270222 0.5169234537962833 0.8362181114065216 0.14328413655460936 0.2759641800091652


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [51]:
a = np.arange(0, 10)
print(a)
scalar = np.random.uniform(0,10)
print(scalar)
print(a[(np.abs(a-scalar)).argmin()])

[0 1 2 3 4 5 6 7 8 9]
7.762546323505893
8


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [52]:
RGB = np.zeros(10, [('position',[('x', float),
                                ('y', float)]),
                       
                    ('color',   [('r', float),
                                ('g', float),
                                ('b', float)])])
print(RGB)


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [53]:
vector = np.random.random((100,2))
X,Y = np.atleast_2d(vector[:,0], vector[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.37406589 0.24341002 ... 0.09955482 0.16004333 0.27413768]
 [0.37406589 0.         0.60396367 ... 0.41177443 0.3498252  0.23537928]
 [0.24341002 0.60396367 0.         ... 0.27736451 0.28314436 0.44050357]
 ...
 [0.09955482 0.41177443 0.27736451 ... 0.         0.25928645 0.35965008]
 [0.16004333 0.3498252  0.28314436 ... 0.25928645 0.         0.15739163]
 [0.27413768 0.23537928 0.44050357 ... 0.35965008 0.15739163 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [54]:
a = (np.random.randint(0, 20, 10)).astype(np.float32)
print(a)
b = a.view(np.int32)
b[:] = a
print(b)

[ 1.  5. 15.  8. 13.  6. 13. 10. 11. 12.]
[ 1  5 15  8 13  6 13 10 11 12]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
readFile = np.genfromtxt(s, delimiter=",", dtype=int)
print(readFile)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [56]:
matrix = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(matrix):
    print(index, value)
for index in np.ndindex(matrix.shape):
    print(index, matrix[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [57]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [58]:
matrix = np.zeros((5,5))
np.put(matrix, np.random.choice(range(5*5), 4, replace=False),1)
print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [59]:
a = np.random.rand(5, 10)
mean = a.mean(axis=1, keepdims=True)
b = a - mean
a, b

(array([[0.32374384, 0.95135191, 0.78948314, 0.52641192, 0.80894743,
         0.58238912, 0.09253114, 0.2048346 , 0.49970356, 0.90148788],
        [0.57197252, 0.46497825, 0.50797664, 0.83979199, 0.88657305,
         0.45792226, 0.67553767, 0.53506534, 0.93738505, 0.78461337],
        [0.05433981, 0.66210419, 0.56735511, 0.80507143, 0.59136158,
         0.70263715, 0.79944954, 0.12515202, 0.25571086, 0.28250728],
        [0.76057337, 0.79597937, 0.4799769 , 0.61174603, 0.92680961,
         0.89547236, 0.25882792, 0.29803237, 0.10884483, 0.93474763],
        [0.0688353 , 0.3079676 , 0.0740064 , 0.56071012, 0.59036984,
         0.48137033, 0.7558603 , 0.62105001, 0.44074436, 0.84500812]]),
 array([[-0.24434462,  0.38326346,  0.22139469, -0.04167653,  0.24085897,
          0.01430067, -0.47555732, -0.36325385, -0.06838489,  0.33339943],
        [-0.0942091 , -0.20120337, -0.15820497,  0.17361038,  0.22039144,
         -0.20825936,  0.00935605, -0.13111627,  0.27120344,  0.11843176],
     

#### 59. How to sort an array by the nth column? (★★☆)

In [60]:
a = 100 * np.random.random((5,5))
a, a[a[:,1].argsort()]

(array([[ 8.30146583, 60.88552825, 44.09261757, 45.99452686, 65.45954146],
        [14.9725476 , 93.53076293, 26.26707639, 58.56198141, 80.34301562],
        [71.04633491, 65.15576708, 62.98833551, 53.85293921, 14.12812144],
        [95.70151343, 17.3869991 , 24.2930485 , 20.58565457, 50.59892478],
        [21.08637038, 92.49421809,  0.47857326, 68.99931787, 12.81354284]]),
 array([[95.70151343, 17.3869991 , 24.2930485 , 20.58565457, 50.59892478],
        [ 8.30146583, 60.88552825, 44.09261757, 45.99452686, 65.45954146],
        [71.04633491, 65.15576708, 62.98833551, 53.85293921, 14.12812144],
        [21.08637038, 92.49421809,  0.47857326, 68.99931787, 12.81354284],
        [14.9725476 , 93.53076293, 26.26707639, 58.56198141, 80.34301562]]))

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [61]:
matrix = np.random.randint(0,2,(5,10))
print(matrix)
print((~matrix.any(axis=0)).any())

[[0 0 1 1 1 0 0 1 1 1]
 [1 0 0 0 1 1 0 0 1 0]
 [1 0 0 1 0 0 1 1 1 0]
 [0 0 0 1 1 0 1 0 1 1]
 [0 0 1 0 0 0 1 0 1 0]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [62]:
matrix = np.random.uniform(0,1,10)
print(matrix)
givenValue = 0.5
print()
print(givenValue)
print()
nearestInArray = matrix.flat[np.abs(matrix - givenValue).argmin()]
print(nearestInArray)

[0.73371583 0.9323649  0.33366726 0.54470483 0.7353012  0.75158094
 0.07398807 0.22169078 0.10592325 0.83806384]

0.5

0.5447048326681286


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [63]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [64]:
class arr(np.ndarray):
    def __new__(cls, array, name):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

a = arr(np.arange(10), "ArrayWithName")
print (a.name)

ArrayWithName


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [65]:
vector = np.ones(10)
print(vector)
indicesVec = np.random.randint(0,len(vector),20)
print(indicesVec)
vector += np.bincount(indicesVec, minlength=len(vector))
print(vector)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 0 5 0 3 8 9 1 7 5 9 6 7 1 4 8 8 9 7]
[3. 3. 1. 2. 2. 5. 2. 4. 4. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [66]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [67]:
w, h = 256, 256
i = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(i.reshape(-1, 3), axis=0)
len(colors)

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [68]:
a = np.random.randint(0,10,(4, 4, 4, 4))
a.sum(axis=(-2,-1))

array([[44, 73, 71, 69],
       [53, 57, 90, 80],
       [60, 73, 78, 62],
       [88, 75, 59, 69]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [69]:
d = np.random.uniform(0, 1, 100)
s = np.random.randint(0, 10, 100)
sums = np.bincount(s, weights=d)
counts = np.bincount(s)
means = sums / counts
means

array([0.48095199, 0.64106353, 0.36206181, 0.4201029 , 0.48719303,
       0.4468518 , 0.61047817, 0.43371053, 0.42827386, 0.51848095])

#### 69. How to get the diagonal of a dot product? (★★★)

In [70]:
a = np.random.uniform(0, 1, (5,5))
b = np.random.uniform(0, 1, (5,5))

np.diag(np.dot(a, b))

array([1.31649393, 1.60445549, 1.8137641 , 1.7109358 , 1.2032488 ])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [71]:
a = np.arange(1, 6)
target = 3
b = np.zeros(len(a) + (len(a)-1)*(target))
b[::target+1] = a
b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [72]:
a = np.ones((5,5,3))
b = 4 * np.ones((5,5))
print(a * b[:,:,None])

[[[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]

 [[4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]
  [4. 4. 4.]]]


#### 72. How to swap two rows of an array? (★★★)

In [73]:
a = np.arange(0, 10, 1).reshape(2,5)
a[[0,1]] = a[[1,0]]
a

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [74]:
faces = np.random.randint(0, 100, (10,3))
f = np.roll(faces.repeat(2, axis=1), -1, axis=1)
f = f.reshape(len(f) * 3, 2)
f = np.sort(f, axis=1)
np.unique(f.view( dtype=[('p0',f.dtype),('p1',f.dtype)]))

array([( 0, 45), ( 0, 68), ( 8, 75), ( 8, 82), (10, 15), (10, 65),
       (13, 25), (13, 29), (13, 52), (13, 62), (13, 78), (13, 83),
       (15, 43), (15, 65), (15, 80), (21, 99), (25, 62), (29, 52),
       (33, 34), (33, 88), (34, 88), (43, 80), (45, 68), (48, 69),
       (48, 93), (69, 93), (75, 82), (78, 83), (99, 99)],
      dtype=[('p0', '<i4'), ('p1', '<i4')])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [75]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)), c)
a

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [76]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
sliding_window_view(Z, window_shape=4).mean(axis=-1)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5,
       12.5, 13.5, 14.5, 15.5, 16.5, 17.5])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [77]:
Z = np.arange(10)
sliding_window_view(Z, window_shape=3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [78]:
a = np.random.uniform(-1.0,1.0,100)
np.negative(a, out=a)

array([ 0.41498354,  0.74568538, -0.31072963, -0.66680253,  0.29547916,
        0.27361335, -0.0195789 , -0.02885165, -0.10856578, -0.68342325,
       -0.30062938, -0.27687659, -0.63501876,  0.23892234,  0.31377039,
        0.4236388 , -0.42695999, -0.05565296, -0.88405089,  0.21123824,
       -0.90895686, -0.53449605,  0.2253949 , -0.67114271,  0.94989401,
       -0.84099991,  0.30138689,  0.44526824,  0.28808205,  0.73409413,
       -0.70714579,  0.3606324 ,  0.44796141, -0.48402407,  0.49890012,
        0.1938322 , -0.18236232,  0.83846466, -0.18684385,  0.63442039,
        0.29155314,  0.17668717,  0.96512177,  0.75350929,  0.24723946,
       -0.25435326,  0.41920632,  0.26036893, -0.14037184, -0.79330458,
       -0.19851562, -0.39361558,  0.99754761, -0.23266598, -0.58999115,
        0.45733735,  0.49523816, -0.98573372,  0.13137734, -0.56229964,
        0.6428936 ,  0.56063309,  0.2217216 , -0.96551636, -0.55324231,
        0.96493006, -0.23107104,  0.65767097, -0.09355679,  0.95

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [79]:
Z = np.arange(1, 15, dtype=np.uint32)
sliding_window_view(Z, window_shape=4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★)

In [80]:
a = np.random.uniform(0, 1, (10, 10))
np.linalg.matrix_rank(a)

10

#### 83. How to find the most frequent value in an array?

In [81]:
a = np.random.randint(0, 10, 50)
print(a)
np.bincount(a).argmax()

[1 8 2 2 7 4 1 1 2 8 7 2 2 0 1 8 4 2 2 7 1 8 1 2 3 5 0 2 5 5 3 3 5 7 3 3 9
 9 5 9 8 2 8 7 0 2 1 9 4 5]


2

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [82]:
a = np.random.randint(0, 10, (10, 10))
sliding_window_view(a, window_shape=(3, 3))

array([[[[9, 0, 1],
         [9, 9, 5],
         [5, 9, 3]],

        [[0, 1, 6],
         [9, 5, 3],
         [9, 3, 2]],

        [[1, 6, 0],
         [5, 3, 3],
         [3, 2, 7]],

        [[6, 0, 8],
         [3, 3, 9],
         [2, 7, 8]],

        [[0, 8, 8],
         [3, 9, 9],
         [7, 8, 8]],

        [[8, 8, 8],
         [9, 9, 7],
         [8, 8, 7]],

        [[8, 8, 4],
         [9, 7, 3],
         [8, 7, 2]],

        [[8, 4, 0],
         [7, 3, 5],
         [7, 2, 3]]],


       [[[9, 9, 5],
         [5, 9, 3],
         [9, 5, 7]],

        [[9, 5, 3],
         [9, 3, 2],
         [5, 7, 2]],

        [[5, 3, 3],
         [3, 2, 7],
         [7, 2, 7]],

        [[3, 3, 9],
         [2, 7, 8],
         [2, 7, 0]],

        [[3, 9, 9],
         [7, 8, 8],
         [7, 0, 1]],

        [[9, 9, 7],
         [8, 8, 7],
         [0, 1, 3]],

        [[9, 7, 3],
         [8, 7, 2],
         [1, 3, 4]],

        [[7, 3, 5],
         [7, 2, 3],
         [3, 4, 8]]],


    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [83]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(a):
    return np.asarray(a + a.T - np.diag(a.diagonal())).view(Symetric)

a = symetric(np.random.randint(0, 10, (10, 10)))
a[1, 2] = 228
a

Symetric([[  1,   6,  14,   3,   9,   6,  17,  12,  10,   9],
          [  6,   4, 228,  13,   5,   9,  11,   6,   5,  14],
          [ 14, 228,   6,   5,   3,   8,  11,  11,   8,  10],
          [  3,  13,   5,   1,   2,  16,  11,  14,   5,  13],
          [  9,   5,   3,   2,   5,   8,  14,   8,   9,   9],
          [  6,   9,   8,  16,   8,   8,  15,   1,   3,   6],
          [ 17,  11,  11,  11,  14,  15,   7,  10,   6,   4],
          [ 12,   6,  11,  14,   8,   1,  10,   2,  11,  15],
          [ 10,   5,   8,   5,   9,   3,   6,  11,   6,   6],
          [  9,  14,  10,  13,   9,   6,   4,  15,   6,   1]])

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [84]:
a = np.ones((16, 16))
sliding_window_view(a, window_shape=(4, 4))[::4, ::4].sum(axis=(-2, -1))

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [85]:
a = np.arange(100)
n = 10
print(a[np.argsort(a)[-n:]])

[90 91 92 93 94 95 96 97 98 99]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [86]:
a = np.array([("first", 1, 3),
              ("second", 2, 4)])
records = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
records

rec.array([(b'first', 1., 3), (b'second', 2., 4)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [87]:
a = np.random.rand(int(5e6))

%timeit np.power(a,3)
%timeit a*a*a
%timeit np.einsum('i,i,i->i',a,a,a)

192 ms ± 3.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
34.3 ms ± 594 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
19.6 ms ± 288 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [88]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
rows

array([0, 3, 4, 6], dtype=int64)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [89]:
a = np.random.randint(0, 10,(10,3))
a[~(np.all(a[:,1:] == a[:,:-1], axis=1))]

array([[0, 5, 6],
       [7, 9, 2],
       [7, 5, 3],
       [9, 6, 6],
       [1, 2, 6],
       [7, 7, 9],
       [4, 5, 3],
       [6, 7, 3],
       [0, 0, 3],
       [5, 0, 5]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [90]:
a = np.array([0, 1, 2, 4, 8, 16, 32, 64, 128], dtype=np.uint8)
np.unpackbits(a[:, np.newaxis], axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [91]:
a = np.random.randint(0, 10, (2, 4))
np.unique(a, axis=0)

array([[1, 2, 5, 0],
       [2, 6, 7, 2]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [92]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.13380885, 0.25139873, 0.08208098, 0.09344477, 0.14101175,
        0.32108383, 0.30014586, 0.09988177, 0.35989578, 0.45303204],
       [0.19198388, 0.36069739, 0.11776669, 0.13407102, 0.20231833,
        0.46067894, 0.43063793, 0.14330658, 0.51636486, 0.64999325],
       [0.06882062, 0.1292995 , 0.04221592, 0.04806055, 0.07252522,
        0.16513997, 0.15437115, 0.05137123, 0.18510175, 0.23300364],
       [0.14298784, 0.26864413, 0.08771155, 0.09985487, 0.15068485,
        0.34310947, 0.32073521, 0.10673344, 0.38458384, 0.48410905],
       [0.05619418, 0.10557706, 0.03447061, 0.03924294, 0.0592191 ,
        0.13484192, 0.12604884, 0.04194621, 0.15114134, 0.19025471],
       [0.00712395, 0.0133844 , 0.00436997, 0.00497497, 0.00750743,
        0.01709442, 0.01597968, 0.00531768, 0.01916075, 0.0241193 ],
       [0.26435882, 0.49667471, 0.1621629 , 0.18461371, 0.2785892 ,
        0.63434775, 0.59298175, 0.19733094, 0.7110264 , 0.89503062],
       [0.14992623, 0.28167991, 0.0919677

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [93]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [94]:
X = np.asarray([[4.0, 2.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [95]:
a = np.random.randn(100)
n = 1000
idx = np.random.randint(0, a.size, (n, a.size))
means = a[idx].mean(axis=1)
confint = np.percentile(means, [3.1, 85.2])
print(confint)

[-0.16059313  0.15460885]
